module.exports = [
  {
    id: 1,
    title: '프리온보딩 백엔드 코스',
    username: '김코딩',
    userId: 1,
    body: '원티드 X 위코드 프리온보딩 백엔드 코스는 전공자, 주니어 경력자, 부트캠프등을 통해 일정 수준 이상의 기술역량을 갖춘 인재들의 graduate school로서, 단기간에 참기기업의 실전과제와 팀단위 동료학습을 통한 역량 향상과 취업을 목표로 하고 있습니다.',
  },
  {
    id: 2,
    title: '안녕하세요!',
    username: 'Guest',
    userId: 0,
    body: '잘 부탁 드립니다!',
  },
  {
    id: 3,
    title: '백엔드 개발자',
    username: 'Guest',
    userId: 0,
    body: '김민재 입니다.',
  },
  {
    id: 4,
    title: '테스트1',
    username: 'Guest',
    userId: 0,
    body: '1번 테스트 입니다.',
  },
  {
    id: 5,
    title: '테스트2',
    username: 'Guest',
    userId: 0,
    body: '2번 테스트 입니다.',
  },
  {
    id: 6,
    title: '테스트3',
    username: 'Guest',
    userId: 0,
    body: '3번 테스트 입니다.',
  },
  {
    id: 7,
    title: '테스트4',
    username: 'Guest',
    userId: 0,
    body: '4번 테스트 입니다.',
  },
  {
    id: 8,
    title: '테스트5',
    username: 'Guest',
    userId: 0,
    body: '5번 테스트 입니다.',
  },
  {
    id: 9,
    title: '테스트6',
    username: 'Guest',
    userId: 0,
    body: '6번 테스트 입니다.',
  },
  {
    id: 10,
    title: '테스트7',
    username: 'Guest',
    userId: 0,
    body: '7번 테스트 입니다.',
  },
  {
    id: 11,
    title: '테스트8',
    username: 'Guest',
    userId: 0,
    body: '8번 테스트 입니다.',
  },
  {
    id: 12,
    title: '테스트9',
    username: 'Guest',
    userId: 0,
    body: '9번 테스트 입니다.',
  },
  {
    id: 13,
    title: '테스트10',
    username: 'Guest',
    userId: 0,
    body: '10번 테스트 입니다.',
  },
  {
    id: 14,
    title: '테스트11',
    username: 'Guest',
    userId: 0,
    body: '11번 테스트 입니다.',
  },
  {
    id: 15,
    title: '테스트12',
    username: 'Guest',
    userId: 0,
    body: '12번 테스트 입니다.',
  },
  {
    id: 16,
    title: '테스트13',
    username: 'Guest',
    userId: 0,
    body: '13번 테스트 입니다.',
  },
  {
    id: 17,
    title: '테스트14',
    username: 'Guest',
    userId: 0,
    body: '14번 테스트 입니다.',
  },
  {
    id: 18,
    title: '테스트15',
    username: 'Guest',
    userId: 0,
    body: '15번 테스트 입니다.',
  },
  {
    id: 19,
    title: '테스트16',
    username: 'Guest',
    userId: 0,
    body: '16번 테스트 입니다.',
  },
  {
    id: 20,
    title: '테스트17',
    username: 'Guest',
    userId: 0,
    body: '17번 테스트 입니다.',
  },
  {
    id: 21,
    title: '테스트18',
    username: 'Guest',
    userId: 0,
    body: '18번 테스트 입니다.',
  },
  {
    id: 22,
    title: '테스트19',
    username: 'Guest',
    userId: 0,
    body: '19번 테스트 입니다.',
  },
  {
    id: 23,
    title: '테스트20',
    username: 'Guest',
    userId: 0,
    body: '20번 테스트 입니다.',
  },
];
